-- -- 1
-- SELECT NAME
-- FROM DEPARTMENTS
-- ORDER BY ID DESC;

-- -- 2
-- SELECT NAME, RATING 
-- FROM GROUPS

-- -- 3
-- SELECT PREMIUM * 100 / SALARY AS PERCENT
-- FROM TEACHERS

-- -- 4
-- SELECT 'The dean of faculty ' || NAME || ' is ' || DEAN || '.' AS FACULTIES_INFO
-- FROM FACULTIES;


-- -- 5
-- SELECT * FROM TEACHERS
-- WHERE SALARY > 3000


-- -- 6
-- SELECT * FROM DEPARTMENTS
-- WHERE FINANCING BETWEEN '10000.00'::MONEY AND '20000.00'::MONEY

-- -- 7
-- SELECT * FROM FACULTIES
-- WHERE NAME != 'SCIENCE'

-- -- 8
-- SELECT NAME, SURNAME 
-- FROM TEACHERS
-- WHERE ISPROFESSOR = FALSE


-- -- 9
-- SELECT * FROM TEACHERS
-- WHERE ISASSISTANT = 'TRUE'
-- AND PREMIUM::MONEY
-- BETWEEN '100.00'::MONEY AND '250.00'::MONEY

-- -- 10
-- SELECT SURNAME, SALARY FROM TEACHERS
-- WHERE ISASSISTANT = 'TRUE'

-- -- 11
-- SELECT SURNAME, POSITION FROM TEACHERS
-- WHERE ISPROFESSOR = 'TRUE'
-- AND EMPLOYMENT_DATE > '2000-01-01'

-- -- 12
-- SELECT NAME FROM DEPARTMENTS AS NAME_OF_DEPARTMENT
-- ORDER BY NAME

-- -- 13
-- SELECT SURNAME 
-- FROM TEACHERS
-- WHERE ISASSISTANT = 'TRUE'
-- AND SALARY + PREMIUM < 10000


-- -- 14
-- SELECT NAME
-- FROM GROUPS
-- WHERE YEAR = 3
-- AND RATING BETWEEN 2 AND 4

-- -- 15
-- SELECT SURNAME FROM TEACHERS
-- WHERE ISASSISTANT = 'TRUE'
-- AND SALARY < 1500 OR 
-- PREMIUM > 400
